{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thredds.fullname" . }}-contents
spec:
  accessModes: 
    - {{ .Values.persistence.accessModes | join "," }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
